### ISSUE TITLE
Fails when using --positionFunction and --modFunction together

### ISSUE THREAD

**Issue by joewdavies** [eurostat/gridtiler#8]
```cmd
$ gridtiler -i ../assets/pop_5000m.csv -r 5000 -a 4 --positionFunction "const a=c.GRD_ID.split('N')[1].split('E');return {x:a[1],y:a[0]};" --modFunction "delete c.GRD_ID"
Load CSV data...
   182321 cells loaded
Modify cells...
Get cell positions...
undefined:3
const a=c.GRD_ID.split('N')[1].split('E');return {x:a[1],y:a[0]};
                 ^

TypeError: Cannot read properties of undefined (reading 'split')
    at eval (eval at <anonymous> (file:///F:/Github/gridtiler/npm/src/index.js:36:36), <anonymous>:3:18)
    at CsvParserStream.<anonymous> (file:///F:/Github/gridtiler/npm/src/index.js:38:33)
    at CsvParserStream.emit (node:events:513:28)
    at CsvParserStream.emit (F:\Github\gridtiler\npm\node_modules\@fast-csv\parse\build\src\CsvParserStream.js:45:23)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by joewdavies** [comment]
Fixed in https://github.com/eurostat/gridtiler/commit/6af059d283d37909eb6e470b5e109c1c3b472d5e
